// context.mjs — assembles the objects a plan script uses, and owns the exit.
//
// The entry script the ego runtime reads comes from stdin, so it has no base
// URL and cannot use relative imports. It is generated by `bin/b2b-test` and
// does exactly three things: import this file by absolute URL, hand it the
// job file, and let it set the process exit code.

import { nowIso, readJson, writeText, nodePath, exists } from "./util.mjs";
import { createRecorder, createCaseDir, EXIT_CODE } from "./recorder.mjs";
import { ensureDir } from "./util.mjs";
import { createSession, envSlugFor } from "./session.mjs";
import { createJev } from "./jev.mjs";
import { renderCase, renderDashboard, toJUnit } from "./report.mjs";
import { autoFormAsk, scriptedAsk } from "./mock-ask.mjs";
import * as helpers from "./helpers.mjs";

export const PAYLOAD_SCHEMA = 1;

/** Assemble the runner object graph and publish it as `globalThis.B2B`. */
export async function buildContext(payload) {
  if (!payload || payload.schema !== PAYLOAD_SCHEMA) {
    throw new Error(
      `job payload schema mismatch (got ${payload?.schema}, expected ${PAYLOAD_SCHEMA})`,
    );
  }

  const rec = createRecorder({
    dataDir: payload.dataDir,
    batchDir: payload.batchDir,
    caseDir: payload.caseDir,
    caseId: payload.caseId,
    slug: payload.slug,
    batchId: payload.batchId,
    url: payload.url,
    description: payload.description,
    env: payload.env,
    agent: payload.agent,
    engine: payload.engine,
    options: payload.options || {},
  });

  const session = createSession({
    dataDir: payload.dataDir,
    envSlug: payload.envSlug || envSlugFor({ url: payload.url, envName: payload.env }),
    url: payload.url,
    name: payload.spaceName || `b2b-web-test ${payload.envSlug || ""}`.trim(),
    mode: payload.options?.session === "fresh" ? "fresh" : "reuse",
    recorder: rec,
  });

  const mockAsk =
    payload.options?.mock === true
      ? Array.isArray(payload.options.mockScript) && payload.options.mockScript.length
        ? scriptedAsk(payload.options.mockScript)
        : autoFormAsk()
      : null;

  const jev = createJev({
    secrets: payload.secrets || {},
    recorder: rec,
    getPage: async () => {
      const { page } = await session.open();
      return page;
    },
    defaults: {
      planner: payload.options?.planner || payload.agent || "unspecified-agent",
      maxSteps: payload.options?.maxSteps ?? 20,
      mock: payload.options?.mock === true,
      mockAsk,
    },
  });

  // Deliberately no secrets in ctx: a plan may log or serialise ctx freely.
  const ctx = {
    schema: PAYLOAD_SCHEMA,
    batchId: payload.batchId,
    caseId: payload.caseId,
    slug: payload.slug,
    url: payload.url,
    description: payload.description,
    env: payload.env || null,
    envSlug: payload.envSlug || null,
    agent: payload.agent || null,
    engine: payload.engine || null,
    caseDir: payload.caseDir,
    batchDir: payload.batchDir,
    dataDir: payload.dataDir,
    skillRoot: payload.skillRoot,
    options: payload.options || {},
    startedAt: nowIso(),
    paths: {
      shots: `${payload.caseDir}/shots`,
      snapshots: `${payload.caseDir}/snapshots`,
      steps: `${payload.caseDir}/steps.jsonl`,
      result: `${payload.caseDir}/result.json`,
    },
    jev: jev.describe(),
  };

  const B2B = {
    schema: PAYLOAD_SCHEMA,
    ctx,
    rec,
    session,
    jev,
    ego: helpers,
    /** Convenience: screenshot the attached page into the record. */
    shot: (label) => rec.shot(label),
    async finish(verdict, reason) {
      return await finalizeContext(B2B, { verdict, reason });
    },
  };
  globalThis.B2B = B2B;
  return B2B;
}

/**
 * Close the case: make sure a verdict exists, write the reports, return an
 * exit code. Safe to call once; a plan calling rec.finish() early wins.
 */
export async function finalizeContext(B2B, { verdict, reason } = {}) {
  const rec = B2B.rec;
  const state = rec.state;
  if (!state.finished) {
    let v = verdict;
    let r = reason;
    if (!v) {
      if (state.verdict) v = state.verdict;
      else if (B2B.session?.handedOff) {
        v = "need-human";
        r = r || "执行过程中交回人工（登录/MFA/验证码等）";
      } else if (state.errors.length) {
        v = "error";
        r = r || state.errors[0].message;
      } else {
        v = "running";
        r = r || "计划脚本结束但没有给出结论";
      }
    }
    await rec.finish(v, r);
  }
  const summary = rec.summary();

  if (B2B.ctx?.options?.junit) {
    try {
      const p = await nodePath();
      const result = await readJson(p.join(summary.caseDir, "result.json"), null);
      if (result) {
        const xml = await toJUnit({ cases: [{ dir: summary.caseDir, result }], suiteName: summary.slug });
        await writeText(p.join(summary.caseDir, "junit.xml"), xml);
      }
    } catch {
      /* JUnit is a nicety, never a failure */
    }
  }

  try {
    await renderDashboard({ dataDir: rec.dataDir });
  } catch {
    /* dashboard is regenerable */
  }

  return EXIT_CODE[summary.verdict] ?? 4;
}

/** Import the plan and run it. Supports default export, `run`, or top-level code. */
export async function runPlan(B2B, planPath) {
  const { pathToFileURL } = await import("node:url");
  if (!(await exists(planPath))) {
    throw new Error(`plan script not found: ${planPath}`);
  }
  const mod = await import(pathToFileURL(planPath).href);
  const fn =
    typeof mod.default === "function"
      ? mod.default
      : typeof mod.run === "function"
        ? mod.run
        : null;
  if (fn) return await fn(B2B);
  return undefined;
}

/**
 * Create the working directory for a case, before anything is executed.
 * Runs through the same runtime as everything else so there is exactly one
 * implementation of what a record looks like.
 */
export async function initCase(payload) {
  const path = await nodePath();
  await ensureDir(payload.batchDir);
  const batchPath = path.join(payload.batchDir, "batch.json");
  let batch = await readJson(batchPath, null);
  if (!batch) {
    batch = {
      batchId: payload.batchId,
      label: payload.label || payload.options?.label || null,
      env: payload.env || null,
      agent: payload.agent || null,
      engine: payload.engine || null,
      createdAt: nowIso(),
      startedAt: nowIso(),
      finishedAt: null,
      summary: { total: 0 },
    };
    await writeText(batchPath, `${JSON.stringify(batch, null, 2)}\n`);
  }
  const created = await createCaseDir({
    batchDir: payload.batchDir,
    batchId: payload.batchId,
    seq: payload.caseSeq || 1,
    slug: payload.slug,
    url: payload.url,
    description: payload.description,
    env: payload.env,
    agent: payload.agent,
    engine: payload.engine,
  });
  return { ...created, batchJson: batchPath, batch };
}

/** Read a job directory written by bin/b2b-test. */
export async function loadJob(jobDir) {
  const path = await nodePath();
  const { readText } = await import("./util.mjs");
  let kv = {};
  try {
    const raw = await readText(path.join(jobDir, "job.env"));
    for (const line of raw.split("\n")) {
      if (!line || line.startsWith("#")) continue;
      const i = line.indexOf("=");
      if (i < 0) continue;
      kv[line.slice(0, i)] = line.slice(i + 1);
    }
  } catch {
    throw new Error(`job file unreadable: ${path.join(jobDir, "job.env")}`);
  }
  const description = await readText(path.join(jobDir, "description.txt")).catch(() => "");
  const bool = (v) => v === "1" || v === "true";
  const payload = {
    schema: Number(kv.schema || PAYLOAD_SCHEMA),
    action: kv.action || "exec",
    skillRoot: kv.skillRoot,
    dataDir: kv.dataDir,
    batchDir: kv.batchDir,
    caseDir: kv.caseDir || null,
    batchId: kv.batchId,
    caseId: kv.caseId || null,
    caseSeq: Number(kv.caseSeq || 1),
    slug: kv.slug,
    url: kv.url,
    description,
    label: kv.label || null,
    env: kv.envName || null,
    envSlug: kv.envSlug || null,
    spaceName: kv.spaceName || null,
    agent: kv.agent || null,
    engine: { ego: kv.engineEgo || null, jev: kv.engineJev || null },
    planPath: kv.planPath || null,
    options: {
      shots: kv.optionsShots || "step",
      session: kv.optionsSession || "reuse",
      maxSteps: kv.optionsMaxSteps ? Number(kv.optionsMaxSteps) : 20,
      mock: bool(kv.optionsMock),
      junit: bool(kv.optionsJunit),
      planner: kv.optionsPlanner || null,
    },
    secrets: {
      backend: kv.secretBackend || null,
      apiKey: kv.secretApiKey || null,
      baseUrl: kv.secretBaseUrl || null,
      model: kv.secretModel || null,
      source: kv.secretSource || null,
    },
  };
  return payload;
}

/**
 * Entry point used by the generated wrapper script.
 * Dispatches on the action, guarantees a record, sets the exit code.
 */
export async function runFromJob({ jobDir }) {
  const payload = await loadJob(jobDir);

  if (payload.action === "init") {
    const created = await initCase(payload);
    process.stdout.write(`B2B_CASE_DIR=${created.caseDir}\n`);
    process.stdout.write(`B2B_CASE_ID=${created.caseId}\n`);
    process.stdout.write(`B2B_PLAN=${created.planPath}\n`);
    return 0;
  }

  if (payload.action === "report") {
    const res = await renderDashboard({ dataDir: payload.dataDir });
    process.stdout.write(`B2B_REPORT=${res.html}\n`);
    return 0;
  }

  if (payload.action === "exec") {
    if (!payload.caseDir) throw new Error("exec: caseDir missing from job");
    const path = await nodePath();
    if (!payload.batchDir) payload.batchDir = path.dirname(path.dirname(payload.caseDir));
    // The record on disk is the source of truth for a re-run: the launcher only
    // has to know which directory to run, never to repeat the case metadata.
    const existing = await readJson(path.join(payload.caseDir, "result.json"), null);
    if (existing) {
      payload.batchId = payload.batchId || existing.batchId;
      payload.caseId = payload.caseId || existing.caseId;
      payload.slug = payload.slug || existing.slug;
      payload.url = payload.url || existing.url;
      if (!payload.description) payload.description = existing.description || "";
      payload.env = payload.env || existing.env || null;
      payload.agent = payload.agent || existing.agent || null;
      if (!payload.engine?.ego) payload.engine = existing.engine || payload.engine;
    }
  }

  let B2B = null;
  let code = 4;
  try {
    B2B = await buildContext(payload);
    await runPlan(B2B, payload.planPath || `${payload.caseDir}/plan.mjs`);
    code = await finalizeContext(B2B);
  } catch (err) {
    try {
      if (B2B) {
        await B2B.rec.error(err);
        code = await finalizeContext(B2B, {
          verdict: "error",
          reason: String(err?.message || err),
        });
      } else {
        console.error(String(err?.stack || err));
      }
    } catch (inner) {
      console.error("b2b-web-test: could not record failure:", String(inner));
      console.error(String(err?.stack || err));
    }
  }
  // The ego runtime collapses any non-zero exit to 1, so the launcher treats
  // exit 1 as "read result.json for the real verdict". Setting it here is
  // still useful when this module is driven by plain node.
  process.exitCode = code;
  return code;
}

export { renderCase, renderDashboard, toJUnit };
